development:
  dialect: postgres
  datasource: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?search_path=${POSTGRES_SCHEMA}&sslmode=${POSTGRES_SSL_MODE}
  dir: migrations
  table: migrations
