services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=deus_user
      - RABBITMQ_DEFAULT_PASS=deus_pass
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq-data:
