services:
  postgres:
    image: postgres:14.7
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cargo_tracker_role -d package_tracker" ]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - POSTGRES_PASSWORD=cargo_tracker
      - POSTGRES_USER=cargo_tracker_role
      - POSTGRES_DB=cargo_tracker
  redis:
    image: redis:7.4.1-alpine3.20
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      - REDIS_PORT=6379

volumes:
  postgres-data:
