// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cargodomainmock

import (
	"context"
	"github.com/soulcodex/deus-cargo-tracker/internal/cargo/domain"
	"sync"
)

// Ensure, that CargoVesselCheckerMock does implement cargodomain.CargoVesselChecker.
// If this is not the case, regenerate this file with moq.
var _ cargodomain.CargoVesselChecker = &CargoVesselCheckerMock{}

// CargoVesselCheckerMock is a mock implementation of cargodomain.CargoVesselChecker.
//
//	func TestSomethingThatUsesCargoVesselChecker(t *testing.T) {
//
//		// make and configure a mocked cargodomain.CargoVesselChecker
//		mockedCargoVesselChecker := &CargoVesselCheckerMock{
//			CheckFunc: func(ctx context.Context, vesselID cargodomain.VesselID) error {
//				panic("mock out the Check method")
//			},
//		}
//
//		// use mockedCargoVesselChecker in code that requires cargodomain.CargoVesselChecker
//		// and then make assertions.
//
//	}
type CargoVesselCheckerMock struct {
	// CheckFunc mocks the Check method.
	CheckFunc func(ctx context.Context, vesselID cargodomain.VesselID) error

	// calls tracks calls to the methods.
	calls struct {
		// Check holds details about calls to the Check method.
		Check []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// VesselID is the vesselID argument value.
			VesselID cargodomain.VesselID
		}
	}
	lockCheck sync.RWMutex
}

// Check calls CheckFunc.
func (mock *CargoVesselCheckerMock) Check(ctx context.Context, vesselID cargodomain.VesselID) error {
	if mock.CheckFunc == nil {
		panic("CargoVesselCheckerMock.CheckFunc: method is nil but CargoVesselChecker.Check was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		VesselID cargodomain.VesselID
	}{
		Ctx:      ctx,
		VesselID: vesselID,
	}
	mock.lockCheck.Lock()
	mock.calls.Check = append(mock.calls.Check, callInfo)
	mock.lockCheck.Unlock()
	return mock.CheckFunc(ctx, vesselID)
}

// CheckCalls gets all the calls that were made to Check.
// Check the length with:
//
//	len(mockedCargoVesselChecker.CheckCalls())
func (mock *CargoVesselCheckerMock) CheckCalls() []struct {
	Ctx      context.Context
	VesselID cargodomain.VesselID
} {
	var calls []struct {
		Ctx      context.Context
		VesselID cargodomain.VesselID
	}
	mock.lockCheck.RLock()
	calls = mock.calls.Check
	mock.lockCheck.RUnlock()
	return calls
}
